// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDH90WRGcOSJq5bO2rol9kWk87AlKzqwNY',
    appId: '1:213215077436:web:cb123600e4a272b1078f39',
    messagingSenderId: '213215077436',
    projectId: 'virajdairy-f9721',
    authDomain: 'virajdairy-f9721.firebaseapp.com',
    storageBucket: 'virajdairy-f9721.firebasestorage.app',
    measurementId: 'G-RR014HLZYT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiYUCd-7-XJ0Fn2F29x24SDLn5S-mugzA',
    appId: '1:213215077436:android:f31a1dc78849c86b078f39',
    messagingSenderId: '213215077436',
    projectId: 'virajdairy-f9721',
    storageBucket: 'virajdairy-f9721.firebasestorage.app',
  );
  
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZY4-B5gjanE0Rv8LLh1XDy6tp541zfbs',
    appId: '1:213215077436:ios:61e567e5949759be078f39',
    messagingSenderId: '213215077436',
    projectId: 'virajdairy-f9721',
    storageBucket: 'virajdairy-f9721.firebasestorage.app',
    iosBundleId: 'com.viraj.dairy.virajDairy',
  );
  
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZY4-B5gjanE0Rv8LLh1XDy6tp541zfbs',
    appId: '1:213215077436:ios:61e567e5949759be078f39',
    messagingSenderId: '213215077436',
    projectId: 'virajdairy-f9721',
    storageBucket: 'virajdairy-f9721.firebasestorage.app',
    iosBundleId: 'com.viraj.dairy.virajDairy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDH90WRGcOSJq5bO2rol9kWk87AlKzqwNY',
    appId: '1:213215077436:web:3ee93c19c85f8b83078f39',
    messagingSenderId: '213215077436',
    projectId: 'virajdairy-f9721',
    authDomain: 'virajdairy-f9721.firebaseapp.com',
    storageBucket: 'virajdairy-f9721.firebasestorage.app',
    measurementId: 'G-7GYG82ZEXW',
  );
}