// =============================================================================
// MAIN ENTRY POINT (lib/main.dart)
// Now just wiring: initialize Firebase, apply the web long-polling fix, and
// hand off to SplashRouter. All screens/services live in their own files.
// =============================================================================

import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'firebase_options.dart'; // generated by running: flutterfire configure
import 'screens/splash_router.dart';
import 'widgets/web_frame_wrapper.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  // Flutter Web's default Firestore transport (WebChannel) is sometimes
  // blocked by antivirus web-shields, ad blockers, or corporate firewalls,
  // which surfaces as "client is offline" even with a working internet
  // connection. Long-polling is slower but far more compatible.
  if (kIsWeb) {
    FirebaseFirestore.instance.settings = const Settings(
      persistenceEnabled: false,
      webExperimentalAutoDetectLongPolling: true,
    );
  }

  runApp(const VirajDairyApp());
}

class VirajDairyApp extends StatelessWidget {
  const VirajDairyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Viraj Dairy',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(primarySwatch: Colors.blue, fontFamily: 'Roboto'),
      home: const WebFrameWrapper(child: SplashRouter()),
    );
  }
}
